version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true  # Move this option to the Sphinx section

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
