version: 2

build:
  os: ubuntu-22.04
  tools:
<<<<<<< HEAD
    python: "3.8"  # Replace with a valid Python version
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"
=======
    python: "3.7.1"
>>>>>>> 2f795dc71feda21108570c73e47d9f6b762e22a4

sphinx:
  configuration: docs/conf.py
<<<<<<< HEAD
  fail_on_warning: true  # Move this option to the Sphinx section
=======
  fail_on_warning: true
>>>>>>> 2f795dc71feda21108570c73e47d9f6b762e22a4

python:
  version: 3.7.1
  install:
    - requirements: docs/requirements.txt
