version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7.1"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  version: 3.7.1
  install:
    - requirements: docs/requirements.txt
